name = "superplace-academy"
compatibility_date = "2024-01-01"

[env.production]
account_id = "117379ce5c9d9af026b16c9cf21b10d5"
workers_dev = false
route = "superplace-academy.pages.dev/*"

[[env.production.d1_databases]]
binding = "DB"
database_name = "superplace-db"
database_id = "your-database-id"
